from selenium.webdriver.common.by import By

CLOSE_DEMO_NAVIGATION_SELECTOR = (By.XPATH, '//button[@class="navigation-close" and @title="Close navigation"]')
CONFIRM_PASSWORD_SELECTOR = (By.XPATH, '//input[@id="password-confirmation-social" and @title="Confirm Password"]')
CREATE_ACCOUNT_SELECTOR = (By.XPATH, '//a[contains(text(), "Create an Account")]')
CREATE_ACCOUNT_BUTTON_SELECTOR = (By.XPATH, '//button[@id="button-create-social" and @title="Create an Account"]')
CREATE_FIRST_NAME_INVALID_SELECTOR = (By.XPATH, '//div[contains(text(), "First Name is not valid!")]')
CREATE_INVALID_PASSWORD_SELECTOR = (By.XPATH, '//div[contains(text(), "Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.")]')
CREATE_LAST_NAME_INVALID_SELECTOR = (By.XPATH, '//div[contains(text(), "Last Name is not valid!")]')
CREATE_SIX_CHARACTER_PASSWORD_SELECTOR = (By.XPATH, '//div[contains(text(), "The password needs at least 8 characters. Create a new password and try again.")]')
CREATE_SHORT_PASSWORD_SELECTOR = (By.XPATH, '//div[@id="password-social-error"]')
EMAIL_ADDRESS_SELECTOR = (By.XPATH, '//input[@id="email_address_create" and @title="Email"]')
ERROR_CREATE_MESSAGE_SELECTOR = (By.XPATH, '//div[contains(text(), "There is already an account with this email address. If you are sure that it is your email address, ")]')
ERROR_INVALID_FIELD_SELECTOR = (By.XPATH, '//div[@id="email_address_create-error"]')
FIRST_NAME_SELECTOR = (By.XPATH, '//input[@id="firstname" and @title="First Name"]')
LAST_NAME_SELECTOR = (By.XPATH, '//input[@id="lastname" and @title="Last Name"]')
PASSWORD_INPUT_SELECTOR = (By.XPATH, '//input[@id="password-social" and @title="Password"]')
WELCOME_MESSAGE_SELECTOR = (By.XPATH, '//span[@class="logged-in"]')
