from selenium.webdriver.common.by import By

CLOSE_DEMO_NAVIGATION_SELECTOR = (By.XPATH, '//button[@class="navigation-close" and @title="Close navigation"]')
LAST_PAGE_NUMBER_SELECTOR = (By.XPATH, '//div[@class="pages"]/ul[@class="items pages-items"]/li[@class="item"][last()]/a/span[last()][last()]')
MAN_BOTTOMS_MENU_SELECTOR = (By.XPATH, '//a[@id="ui-id-18"]')
MAN_MENU_SELECTOR = (By.XPATH, '//li[@class="level0 nav-3 category-item level-top parent ui-menu-item"]')
MAN_PANTS_MENU_SELECTOR = (By.XPATH, '//a[@id="ui-id-19"]')
NEXT_PAGE_SELECTOR = (By.XPATH, '//a[@class="action  next"]')
PRODUCT_CATEGORY_SELECTOR = (By.XPATH, '(//a[contains(text(), "Hoodies & Sweatshirts")])[2]')
PRODUCT_COLOR_SELECTOR = (By.XPATH, '//div[contains(text(), "Color")]')
PRODUCT_COLOR_WHITE_SELECTOR = (By.XPATH, '//div[@class="swatch-option color " and @data-option-label="White"]')
PRODUCT_COLOR_BLUE_SELECTOR = (By.XPATH, '//div[@class="swatch-option color" and @data-option-label="Blue"]')
PRODUCT_ITEM_SELECTOR = (By.XPATH, '//div[@class="product details product-item-details"]')
PRODUCT_NAME_SELECTOR = (By.XPATH, '(//strong[@class="product name product-item-name"])[2]')
PRODUCT_PRESENTATION_IMAGES_SELECTOR = (By.XPATH, '//div[@class="fotorama__thumb fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img"]')
PRODUCT_FINAL_PRICE_SELECTOR = (By.XPATH, '//span[@data-price-type="finalPrice"]')
PRODUCT_PRICE_SELECTOR = (By.XPATH, '//span[@data-price-type="finalPrice"]')
PRODUCT_SIZE_SELECTOR = (By.XPATH, '//div[contains(text(), "Size")]')
PRODUCT_SIZE_34_SELECTOR = (By.XPATH, '//div[@class="swatch-option text" and @data-option-label="34"]')
PRODUCT_SIZE_L_SELECTOR = (By.XPATH, '//div[@class="swatch-option text " and @data-option-label="L"]')
PRODUCT_STYLE_SELECTOR = (By.XPATH, '//div[contains(text(), "Style")]')
PRODUCT_STYLE_SWEATPANTS_SELECTOR = (By.XPATH, '//a[contains(text(), "Sweatpants")]')
SEARCH_BAR_SELECTOR = (By.XPATH, '//input[@id="search" and @class="input-text"]')
SEARCH_BUTTON_SELECTOR = (By.XPATH, '//button[@type="submit" and @class="action search"]')
SEARCH_ERROR_SELECTOR = (By.XPATH, '//div[@class="message notice"]/div[contains(text(), "Your search returned no results. ")]')
SORTING_MENU_SELECTOR = (By.XPATH, '//select[@id="sorter" and @class="sorter-options"]')
TOTAL_ITEMS_ON_PAGE_SELECTOR = (By.XPATH, '//p[@class="toolbar-amount"]/span[2]')
TOTAL_SEARCHED_ITEMS_SELECTOR = (By.XPATH, '//p[@class="toolbar-amount"]/span[last()]')
WHAT_IS_NEW_MENU_SELECTOR = (By.XPATH, '//span[contains(text(), \"What\'s New")]')
