from selenium.webdriver.common.by import By

ACCEPT_AGREEMENT = (By.ID, "agreement__1")
ADD_TO_CART_SELECTOR = (By.XPATH, '//button[@type="submit" and @title="Add to Cart"]')
CART_PRODUCT_NAME_SELECTOR = (By.XPATH, '//strong[@class="product-item-name"]')
CART_PRODUCT_PRICE_SELECTOR = (By.XPATH, '//span[@class="cart-price"]')
CART_SELECTOR = (By.XPATH, '//a[@class="action showcart"]')
CLOSE_DEMO_NAVIGATION_SELECTOR = (By.XPATH, '//button[@class="navigation-close" and @title="Close navigation"]')
CHECKBOX_BILLING_ADDRESS_SELECTOR = (By.XPATH, '//input[@type="checkbox" and @name="billing-address-same-as-shipping"]')
DELETED_ITEMS_MESSAGE_SELECTOR = (By.XPATH, '//span[contains(text(), "You have no items in your shopping cart.")]')
DISCOUNT_AMOUNT_SELECTOR = (By.XPATH, '//span[@data-th="checkout.sidebar.summary.totals.discount"]')
EDIT_ITEM_IN_CART_SELECTOR = (By.XPATH, '//div[@class="primary"]/a[@class="action edit" and @title="Edit item"]')
MAN_BOTTOMS_MENU_SELECTOR = (By.XPATH, '//a[@id="ui-id-23"]')
MAN_MENU_SELECTOR = (By.XPATH, '//li[@class="level0 nav-4 category-item level-top parent ui-menu-item"]')
MAN_PANTS_MENU_SELECTOR = (By.XPATH, '//a[@id="ui-id-24"]')
PLACE_ORDER_SELECTOR = (By.XPATH, '//div[@class="place-order-primary"]/button[@class="action primary checkout" and @type="button"]')
PRODUCT_FIRST_COLOR_SELECTOR = (By.XPATH, '(//div[@class="swatch-option color"])[1]')
PRODUCT_SECOND_COLOR_SELECTOR = (By.XPATH, '(//div[@class="swatch-option color"])[2]')
PRODUCT_NAME_SELECTOR = (By.XPATH, '(//strong[@class="product name product-item-name"])[2]')
PRODUCT_FINAL_PRICE_SELECTOR = (By.XPATH, '//span[@data-price-type="finalPrice"]')
PRODUCT_FIRST_SIZE_SELECTOR = (By.XPATH, '(//div[@class="swatch-option text"])[3]')
PRODUCT_SECOND_SIZE_SELECTOR = (By.XPATH, '(//div[@class="swatch-option text"])[2]')
PRODUCT_STYLE_SELECTOR = (By.XPATH, '//div[contains(text(), "Style")]')
PRODUCT_STYLE_SWEATPANTS_SELECTOR = (By.XPATH, '//a[contains(text(), "Sweatpants")]')
QUANTITY_SELECTOR = (By.XPATH, '//input[@type="number"]')
REMOVE_ITEM_BUTTON_SELECTOR = (By.XPATH, '//button[@class="action-primary action-accept"]')
REMOVE_ITEM_FROM_CART_SELECTOR = (By.XPATH, '//div[@class="secondary"]/a[@class="action delete" and @title="Remove item"]')
SEARCH_BUTTON_SELECTOR = (By.XPATH, '//button[@type="submit" and @class="action search"]')
SEE_DETAILS_SELECTOR = (By.XPATH, '//span[@data-role="title" and @class="toggle"]/span[contains(text(), "See Details")]')
SELECTED_PRODUCT_NAME_SELECTOR = (By.XPATH, '//span[@itemprop="name"]')
SHIPPING_FEE_SELECTOR = (By.XPATH, '//span[@data-th="Shipping"]')
THANKS_MESSAGE_SELECTOR = (By.XPATH, '//h1[@class="page-title"]')
TOTAL_PRODUCT_PRICE_SELECTOR = (By.XPATH, '//strong/span[@data-bind="text: getValue()"]')
UPDATE_CART_SELECTOR = (By.XPATH, '//button[@type="submit" and @title="Update Cart"]')
UPDATE_MESSAGE_SELECTOR = (By.XPATH, '//div[contains(text(), "Geo Insulated Jogging Pant was updated in your shopping cart.")]')
