from selenium.webdriver.common.by import By

CLOSE_DEMO_NAVIGATION_SELECTOR = (By.XPATH, '//button[@class="navigation-close" and @title="Close navigation"]')
FACEBOOCK_ACCEPT_COOKIES_SELECTOR = (By.XPATH, '//button[@data-cookiebanner="accept_button" and @type="submit"] | //span[contains(text(), "Allow all cookies")]')
FACEBOOCK_ERROR_MESSAGE_SELECTOR = (By.XPATH, '//div[@class="fsl fwb fcb" and contains(text(), "Error Accessing App")]')
FACEBOOCK_LOGIN_SELECTOR = (By.XPATH, '//a[@class="btn btn-block btn-social btn-facebook"]')
LINKEDIN_ERROR_MESSAGE_SELECTOR = (By.XPATH, '//p[@class="message"]')
LINKEDIN_LOGIN_SELECTOR = (By.XPATH, '//a[@class="btn btn-block btn-social btn-linkedin"]')
YAHOO_ACCEPT_COOKIES_SELECTOR = (By.XPATH, '//button[@class="pure-button puree-button-primary oauth2-authorize-button"]')
YAHOO_CONFIRM_PASSWORD_SELECTOR = (By.XPATH, '//input[@id="request-password-confirmation"]')
YAHOO_ERROR_MESSAGE_SELECTOR = (By.XPATH, '//div[@class="oauth2-error txt-align-center"]/p[contains(text(), "Looks like something went wrong.")]')
YAHOO_INPUT_PASSWORD_SELECTOR = (By.XPATH, '//input[@id="request-password-social"]')
YAHOO_LOGIN_SELECTOR = (By.XPATH, '//a[@class="btn btn-block btn-social btn-yahoo"]')
YAHOO_NEXT_BUTTON_SELECTOR_1 = (By.XPATH, '//input[@id="login-signin"]')
YAHOO_NEXT_BUTTON_SELECTOR_2 = (By.XPATH, '//button[@id="login-signin"]')
YAHOO_SUBMIT_SELECTOR = (By.XPATH, '//button[@class="action send primary"]')
YAHOO_USER_EMAIL_SELECTOR = (By.XPATH, '//input[@class="phone-no "]')
YAHOO_USER_PASSWORD_SELECTOR = (By.XPATH, '//input[@id="login-passwd" and @class="password"]')
GITHUB_EMAIL_SELECTOR = (By.XPATH, '//input[@class="form-control input-block js-login-field"]')
GITHUB_LOGIN_SELECTOR = (By.XPATH, '//a[@class="btn btn-block btn-social btn-github"]')
GITHUB_PASSWORD_SELECTOR = (By.XPATH, '//input[@class="form-control form-control input-block js-password-field"]')
GITHUB_SIGNIN_BUTTON_SELECTOR = (By.XPATH, '//input[@class="btn btn-primary btn-block js-sign-in-button"]')
SIGNIN_BUTTON_SELECTOR = (By.XPATH, '//button[@id="bnt-social-login-authentication"]')
SIGNIN_EMAIL_SELECTOR = (By.XPATH, '//input[@id="social_login_email"]')
SIGNIN_ERROR_MESSAGE_1 = (By.XPATH, '//div[contains(text(), "Invalid login or password.")]')
SIGNIN_ERROR_MESSAGE_2 = (By.XPATH, '//div[@id="social_login_email-error"]')
SIGNIN_PASSWORD_SELECTOR = (By.XPATH, '//input[@id="social_login_pass"]')
SIGNIN_SELECTOR = (By.XPATH, '//a[contains(text(), "Sign In")]')
SIGN_OUT_BUTTON_SELECTOR = (By.XPATH, '//li[@class="link authorization-link"]')
SIGN_OUT_MENU_SELECTOR = (By.XPATH, '//button[@class="action switch" and @data-action="customer-menu-toggle"]')
SIGN_OUT_MESSAGE_SELECTOR = (By.XPATH, '//span[@data-ui-id="page-title-wrapper"]')
WELCOME_MESSAGE_SELECTOR = (By.XPATH, '//span[@class="logged-in"]')
